### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by haesleinhuepf** [CamachoDejay/Zeiss-OAD-examples#1]
Hi Rafa @CamachoDejay ,

thanks for sharing this publicly! Would you mind adding a license file so that others can reuse the stuff you made? In case no license file is provided, technically no one is allowed to copy the content. BSD and MIT licenses are quite popular and allow others to reuse things flexibly (permissive licensing). If you add a GPL license, others who wish to reuse your code have to publish their code under a GPL license as well (restrictive licensing).

Read more: https://choosealicense.com/

Thanks again and have a great weekend!

Best,
Robert

**Comment by haesleinhuepf** [comment]
Ha never mind, I was looking in the wrong folder 🙌☺️

**Comment by CamachoDejay** [comment]
Maybe I should add a Licence batch to each main readme just to avoid confusion
